# Generated by Django 6.0.7 on 2026-08-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsavings',
            name='payout_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupsavings',
            name='payout_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
