# Generated by Django 6.0.7 on 2026-08-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
